import type { Product, BrandInfo, User } from "../types";

export const MOCK_USER: User = {
  name: "Rahul Sharma",
  email: "rahul.sharma@email.com",
  phone: "+91 98765 43210",
  pan: "ABCPS1234D",
  dob: "15 March 1995",
  address: "Flat 4B, Green Heights, Sector 14, Gurugram, Haryana 122001",
  kycStatus: "verified",
  mfValue: 842500,
  emiLimit: 250000,
  usedLimit: 0,
};

export const BRANDS: BrandInfo[] = [
  { id: "air-india", name: "Air India", category: "Travel & Flights", tagline: "Fly the world on EMI", color: "#C0392B", logo: "✈️" },
  { id: "goibibo", name: "Goibibo", category: "Hotels", tagline: "Hotels & flights on EMI", color: "#E67E22", logo: "🏨" },
  { id: "cgh-earth", name: "CGH Earth", category: "Hotels", tagline: "Luxury resorts on EMI", color: "#27AE60", logo: "🌿" },
  { id: "croma", name: "Croma", category: "Smartphones", tagline: "Electronics on 0% EMI", color: "#8E44AD", logo: "📱" },
  { id: "giva", name: "Giva", category: "Jewelry & Beauty", tagline: "Silver & gold jewelry on EMI", color: "#D4AF37", logo: "💎" },
  { id: "wakefit", name: "Wakefit", category: "Furniture & Home", tagline: "Sleep better, pay easier", color: "#2ECC71", logo: "🛏️" },
  { id: "apple", name: "Apple", category: "Smartphones", tagline: "iPhone & Mac on EMI", color: "#1d1d1f", logo: "🍎" },
  { id: "samsung", name: "Samsung", category: "Smartphones", tagline: "Galaxy series on EMI", color: "#1428A0", logo: "📲" },
  { id: "mytrip", name: "MakeMyTrip", category: "Travel & Flights", tagline: "Holidays on easy EMI", color: "#E84848", logo: "🗺️" },
  { id: "easemytrip", name: "EaseMyTrip", category: "Travel & Flights", tagline: "Low cost flights on EMI", color: "#3498DB", logo: "🛫" },
  { id: "sony", name: "Sony", category: "Audio", tagline: "Audio & TVs on EMI", color: "#003087", logo: "🎧" },
  { id: "urban-company", name: "Urban Company", category: "Jewelry & Beauty", tagline: "Beauty services on EMI", color: "#FF6B35", logo: "💅" },
  { id: "ikea", name: "IKEA", category: "Furniture & Home", tagline: "Home furnishing on EMI", color: "#0051BA", logo: "🪑" },
  { id: "yatra", name: "Yatra", category: "Travel & Flights", tagline: "Travel packages on EMI", color: "#E91E8C", logo: "🌏" },
  { id: "dell", name: "Dell", category: "Laptops", tagline: "Laptops & PCs on EMI", color: "#007DB8", logo: "💻" },
  { id: "lg", name: "LG", category: "Appliances", tagline: "Home appliances on EMI", color: "#A50034", logo: "🏠" },
  { id: "whirlpool", name: "Whirlpool", category: "Appliances", tagline: "Washers & fridges on EMI", color: "#00539C", logo: "🧺" },
  { id: "playstation", name: "PlayStation", category: "Gaming", tagline: "Play now, pay later", color: "#003087", logo: "🎮" },
  { id: "garmin", name: "Garmin", category: "Fitness", tagline: "Fitness trackers on EMI", color: "#007DC3", logo: "🏃" },
  { id: "canon", name: "Canon", category: "Cameras", tagline: "Cameras & lenses on EMI", color: "#CC0000", logo: "📷" },
];

export const MOCK_PRODUCTS: Product[] = [
  // ── SMARTPHONES ──────────────────────────────────────────────────
  {
    id: "pixel-10",
    name: "Pixel 10",
    brand: "Google",
    category: "Smartphones",
    rating: 4.6,
    badge: "New Launch",
    basePrice: 74999,
    description: "Google's flagship with Gemini AI built-in, stunning camera system, and the cleanest Android experience. Powered by Tensor G5.",
    images: ["https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=600&h=600&fit=crop", "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=600&h=600&fit=crop"],
    specifications: { Display: "6.3″ AMOLED 120Hz", Processor: "Tensor G5", RAM: "12GB", Battery: "4700 mAh", Camera: "50MP + 48MP", OS: "Android 16" },
    variants: [
      { id: "pixel-10-128", label: "128GB / Obsidian", priceDelta: 0, inStock: true },
      { id: "pixel-10-256", label: "256GB / Porcelain", priceDelta: 5000, inStock: true },
      { id: "pixel-10-512", label: "512GB / Hazel", priceDelta: 10000, inStock: false },
    ],
  },
  {
    id: "iphone-17",
    name: "iPhone 17",
    brand: "Apple",
    category: "Smartphones",
    rating: 4.8,
    badge: "Bestseller",
    basePrice: 89999,
    description: "The thinnest iPhone ever. Camera Control, A19 chip, and Apple Intelligence.",
    images: ["https://images.unsplash.com/photo-1591337676887-a217a6970a8a?w=600&h=600&fit=crop", "https://images.unsplash.com/photo-1611472173362-3f53dbd65d80?w=600&h=600&fit=crop"],
    specifications: { Display: "6.1″ Super Retina XDR", Processor: "A19", RAM: "8GB", Battery: "3960 mAh", Camera: "48MP + 12MP", OS: "iOS 19" },
    variants: [
      { id: "ip17-128-black", label: "128GB / Black", priceDelta: 0, inStock: true },
      { id: "ip17-256-white", label: "256GB / White", priceDelta: 8000, inStock: true },
      { id: "ip17-512-desert", label: "512GB / Desert Titanium", priceDelta: 20000, inStock: true },
    ],
  },
  {
    id: "iphone-17-pro",
    name: "iPhone 17 Pro",
    brand: "Apple",
    category: "Smartphones",
    rating: 4.9,
    badge: "Top Pick",
    basePrice: 134999,
    description: "Pro camera system with 5x telephoto. Titanium design, ProMotion 120Hz, and all-day battery.",
    images: ["https://images.unsplash.com/photo-1658203897339-0b8c64a42fba?w=600&h=600&fit=crop", "https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?w=600&h=600&fit=crop"],
    specifications: { Display: "6.3″ LTPO 120Hz", Processor: "A19 Pro", RAM: "12GB", Battery: "4422 mAh", Camera: "48MP + 48MP UW + 12MP 5x", OS: "iOS 19" },
    variants: [
      { id: "ip17pro-256-nat", label: "256GB / Natural Titanium", priceDelta: 0, inStock: true },
      { id: "ip17pro-512-black", label: "512GB / Black Titanium", priceDelta: 12000, inStock: true },
      { id: "ip17pro-1tb-white", label: "1TB / White Titanium", priceDelta: 28000, inStock: false },
    ],
  },
  {
    id: "samsung-s25",
    name: "Galaxy S25",
    brand: "Samsung",
    category: "Smartphones",
    rating: 4.5,
    basePrice: 79999,
    description: "Galaxy AI + Snapdragon 8 Elite. Flagship camera, all-day battery.",
    images: ["https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=600&h=600&fit=crop"],
    specifications: { Display: "6.2″ Dynamic AMOLED 120Hz", Processor: "Snapdragon 8 Elite", RAM: "12GB", Battery: "4000 mAh", Camera: "50MP triple", OS: "One UI 7" },
    variants: [
      { id: "s25-128-gray", label: "128GB / Titanium Gray", priceDelta: 0, inStock: true },
      { id: "s25-256-blue", label: "256GB / Titanium Blue", priceDelta: 6000, inStock: true },
    ],
  },
  {
    id: "samsung-s25-ultra",
    name: "Galaxy S25 Ultra",
    brand: "Samsung",
    category: "Smartphones",
    rating: 4.7,
    badge: "New Launch",
    basePrice: 129999,
    description: "The ultimate Galaxy. 200MP camera, built-in S Pen, titanium frame, and AI you can trust.",
    images: ["https://images.unsplash.com/photo-1565849904461-04a58ad377e0?w=600&h=600&fit=crop"],
    specifications: { Display: "6.9″ Dynamic AMOLED 120Hz", Processor: "Snapdragon 8 Elite", RAM: "12GB", Camera: "200MP + 50MP + 10MP + 50MP", "S Pen": "Built-in", Battery: "5000 mAh" },
    variants: [
      { id: "s25u-256-titanium", label: "256GB / Titanium Silver", priceDelta: 0, inStock: true },
      { id: "s25u-512-black", label: "512GB / Titanium Black", priceDelta: 15000, inStock: true },
      { id: "s25u-1tb-gray", label: "1TB / Titanium Gray", priceDelta: 30000, inStock: true },
    ],
  },
  {
    id: "oneplus-13",
    name: "OnePlus 13",
    brand: "OnePlus",
    category: "Smartphones",
    rating: 4.5,
    basePrice: 69999,
    description: "Hasselblad camera system, Snapdragon 8 Elite, 100W SUPERVOOC charging. Performance flagship at a competitive price.",
    images: ["https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=600&h=600&fit=crop"],
    specifications: { Display: "6.82″ LTPO AMOLED 120Hz", Processor: "Snapdragon 8 Elite", RAM: "16GB", Camera: "50MP Hasselblad triple", Charging: "100W + 50W wireless", Battery: "6000 mAh" },
    variants: [
      { id: "op13-256-black", label: "256GB / Midnight Ocean", priceDelta: 0, inStock: true },
      { id: "op13-512-white", label: "512GB / Arctic Dawn", priceDelta: 8000, inStock: true },
    ],
  },
  // ── LAPTOPS ──────────────────────────────────────────────────────
  {
    id: "macbook-air-m4",
    name: "MacBook Air M4",
    brand: "Apple",
    category: "Laptops",
    rating: 4.8,
    badge: "New Launch",
    basePrice: 109999,
    description: "Impossibly thin, impossibly fast. M4 chip, 18-hour battery, Liquid Retina display.",
    images: ["https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600&h=600&fit=crop", "https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?w=600&h=600&fit=crop"],
    specifications: { Display: '13.6" Liquid Retina', Processor: "Apple M4", RAM: "16GB", Storage: "256GB SSD", Battery: "18 hours", Weight: "1.24 kg" },
    variants: [
      { id: "mba-m4-16-256", label: "16GB / 256GB / Midnight", priceDelta: 0, inStock: true },
      { id: "mba-m4-16-512", label: "16GB / 512GB / Starlight", priceDelta: 10000, inStock: true },
      { id: "mba-m4-24-1tb", label: "24GB / 1TB / Sky Blue", priceDelta: 30000, inStock: true },
    ],
  },
  {
    id: "macbook-pro-m4",
    name: "MacBook Pro 14 M4",
    brand: "Apple",
    category: "Laptops",
    rating: 4.9,
    badge: "Top Pick",
    basePrice: 169999,
    description: "The most powerful MacBook Pro ever. M4 Pro chip, Liquid Retina XDR display, 22-hour battery.",
    images: ["https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=600&h=600&fit=crop"],
    specifications: { Display: '14.2" Liquid Retina XDR', Processor: "Apple M4 Pro", RAM: "24GB", Storage: "512GB SSD", Battery: "22 hours", Ports: "3× Thunderbolt 5" },
    variants: [
      { id: "mbp14-24-512-black", label: "24GB / 512GB / Space Black", priceDelta: 0, inStock: true },
      { id: "mbp14-48-1tb-silver", label: "48GB / 1TB / Silver", priceDelta: 40000, inStock: true },
    ],
  },
  {
    id: "dell-xps-15",
    name: "XPS 15",
    brand: "Dell",
    category: "Laptops",
    rating: 4.6,
    basePrice: 149999,
    description: "OLED InfinityEdge display, Intel Core Ultra 9, RTX 4070. The preferred laptop of creators.",
    images: ["https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=600&h=600&fit=crop"],
    specifications: { Display: '15.6" OLED 3.5K 120Hz', Processor: "Core Ultra 9", RAM: "32GB", Storage: "1TB SSD", GPU: "RTX 4070 8GB", Battery: "86Wh" },
    variants: [
      { id: "xps15-32-1tb", label: "32GB / 1TB / Platinum", priceDelta: 0, inStock: true },
      { id: "xps15-64-2tb", label: "64GB / 2TB / Obsidian", priceDelta: 30000, inStock: true },
    ],
  },
  {
    id: "dell-inspiron-15",
    name: "Inspiron 15",
    brand: "Dell",
    category: "Laptops",
    rating: 4.3,
    basePrice: 54999,
    description: "Everyday laptop for work and study. 12th Gen Intel, Full HD display, 8-hour battery. Great value.",
    images: ["https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?w=600&h=600&fit=crop"],
    specifications: { Display: '15.6" FHD IPS', Processor: "Intel i5-12th Gen", RAM: "16GB", Storage: "512GB SSD", Battery: "8 hours", OS: "Windows 11" },
    variants: [
      { id: "ins15-16-512-silver", label: "16GB / 512GB / Silver", priceDelta: 0, inStock: true },
      { id: "ins15-32-1tb-black", label: "32GB / 1TB / Black", priceDelta: 10000, inStock: true },
    ],
  },
  // ── AUDIO ────────────────────────────────────────────────────────
  {
    id: "sony-wh1000xm6",
    name: "WH-1000XM6",
    brand: "Sony",
    category: "Audio",
    rating: 4.7,
    badge: "Bestseller",
    basePrice: 29990,
    description: "Industry-leading noise cancellation, 40-hour battery, LDAC lossless audio.",
    images: ["https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&h=600&fit=crop", "https://images.unsplash.com/photo-1484704849700-f032a568e944?w=600&h=600&fit=crop"],
    specifications: { Driver: "40mm", "Noise Cancellation": "Adaptive", Battery: "40 hours", Codec: "LDAC / AAC / SBC", Connectivity: "Bluetooth 5.3" },
    variants: [
      { id: "xm6-black", label: "Midnight Black", priceDelta: 0, inStock: true },
      { id: "xm6-silver", label: "Platinum Silver", priceDelta: 1000, inStock: true },
    ],
  },
  {
    id: "bose-qc45",
    name: "QuietComfort 45",
    brand: "Bose",
    category: "Audio",
    rating: 4.6,
    basePrice: 24999,
    description: "World-class Bose noise cancellation. 24 hours of battery. Whisper-quiet performance with Aware Mode.",
    images: ["https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=600&h=600&fit=crop"],
    specifications: { "Noise Cancellation": "QuietComfort", Battery: "24 hours", Codec: "AAC / SBC", Microphone: "4 mics", Weight: "238g" },
    variants: [
      { id: "qc45-white", label: "White Smoke", priceDelta: 0, inStock: true },
      { id: "qc45-black", label: "Triple Black", priceDelta: 0, inStock: true },
    ],
  },
  {
    id: "airpods-pro3",
    name: "AirPods Pro 3",
    brand: "Apple",
    category: "Audio",
    rating: 4.8,
    badge: "New Launch",
    basePrice: 26900,
    description: "Next-level Active Noise Cancellation. Hearing Aid feature. H2 chip. 30-hour total battery with case.",
    images: ["https://images.unsplash.com/photo-1572569511254-d8f925fe2cbb?w=600&h=600&fit=crop", "https://images.unsplash.com/photo-1606841837239-c5a1a4a07af7?w=600&h=600&fit=crop"],
    specifications: { Chip: "Apple H2", ANC: "Adaptive Transparency", Battery: "6h + 24h case", Water: "IPX4", "Hearing Aid": "Yes", Spatial: "Personalized" },
    variants: [
      { id: "app3-white", label: "White (USB-C case)", priceDelta: 0, inStock: true },
      { id: "app3-midnight", label: "Midnight (MagSafe case)", priceDelta: 1500, inStock: true },
    ],
  },
  // ── TABLETS ──────────────────────────────────────────────────────
  {
    id: "ipad-pro-m4",
    name: "iPad Pro M4",
    brand: "Apple",
    category: "Tablets",
    rating: 4.9,
    basePrice: 99900,
    description: "Ultra Retina XDR OLED at 5.1mm. M4 chip, Apple Pencil Pro support.",
    images: ["https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=600&h=600&fit=crop", "https://images.unsplash.com/photo-1537589376225-5405c60a5bd8?w=600&h=600&fit=crop"],
    specifications: { Display: '11" OLED Ultra Retina XDR', Processor: "Apple M4", RAM: "8GB", Camera: "12MP + LiDAR", Connectivity: "Wi-Fi 6E" },
    variants: [
      { id: "ipadpro-256-silver", label: "256GB / Silver", priceDelta: 0, inStock: true },
      { id: "ipadpro-512-black", label: "512GB / Space Black", priceDelta: 18000, inStock: true },
    ],
  },
  {
    id: "samsung-tab-s10",
    name: "Galaxy Tab S10+",
    brand: "Samsung",
    category: "Tablets",
    rating: 4.6,
    badge: "Bestseller",
    basePrice: 89999,
    description: "12.4-inch Dynamic AMOLED 2X display. Snapdragon 8 Gen 3. S Pen included. Galaxy AI for productivity.",
    images: ["https://images.unsplash.com/photo-1661595676335-aa93ecbf4b42?w=600&h=600&fit=crop", "https://images.unsplash.com/photo-1661595676830-2a0a1ccab283?w=600&h=600&fit=crop"],
    specifications: { Display: '12.4" Dynamic AMOLED 120Hz', Processor: "Snapdragon 8 Gen 3", RAM: "12GB", Storage: "256GB", "S Pen": "Included", Battery: "10090 mAh" },
    variants: [
      { id: "tabs10-256-gray", label: "256GB / Graphite", priceDelta: 0, inStock: true },
      { id: "tabs10-512-silver", label: "512GB / Silver", priceDelta: 12000, inStock: true },
    ],
  },
  // ── TRAVEL ───────────────────────────────────────────────────────
  {
    id: "airindia-mum-del",
    name: "Mumbai → Delhi",
    brand: "Air India",
    category: "Travel & Flights",
    rating: 4.3,
    badge: "Hot Deal",
    basePrice: 4999,
    description: "Direct flight BOM→DEL. 2h 10m. Economy & Business seats. Frequent departures.",
    images: ["https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=600&h=400&fit=crop"],
    specifications: { Route: "BOM → DEL", Duration: "2h 10m", Airline: "Air India", Frequency: "12/day", Baggage: "15kg" },
    variants: [
      { id: "ai-mum-del-eco", label: "Economy Class", priceDelta: 0, inStock: true },
      { id: "ai-mum-del-bus", label: "Business Class", priceDelta: 12000, inStock: true },
    ],
  },
  {
    id: "airindia-del-lon",
    name: "Delhi → London",
    brand: "Air India",
    category: "Travel & Flights",
    rating: 4.4,
    basePrice: 38999,
    description: "Non-stop DEL→LHR. 8h 45m. Dreamliner 787 with in-flight entertainment.",
    images: ["https://images.unsplash.com/photo-1530521954074-e64f6810b32d?w=600&h=400&fit=crop"],
    specifications: { Route: "DEL → LHR", Duration: "8h 45m", Aircraft: "Boeing 787", Meals: "Included", Baggage: "23kg" },
    variants: [
      { id: "ai-del-lon-eco", label: "Economy", priceDelta: 0, inStock: true },
      { id: "ai-del-lon-prem", label: "Premium Economy", priceDelta: 25000, inStock: true },
      { id: "ai-del-lon-bus", label: "Business (Lie-flat)", priceDelta: 85000, inStock: true },
    ],
  },
  {
    id: "airindia-del-dubai",
    name: "Delhi → Dubai",
    brand: "Air India",
    category: "Travel & Flights",
    rating: 4.5,
    badge: "Hot Deal",
    basePrice: 14999,
    description: "Non-stop DEL→DXB. 3h 30m. Great connectivity for business and leisure.",
    images: ["https://images.unsplash.com/photo-1557146799-1d5e5fc65d5c?w=600&h=400&fit=crop"],
    specifications: { Route: "DEL → DXB", Duration: "3h 30m", Airline: "Air India", Meals: "Included", Baggage: "20kg" },
    variants: [
      { id: "ai-del-dxb-eco", label: "Economy", priceDelta: 0, inStock: true },
      { id: "ai-del-dxb-bus", label: "Business", priceDelta: 30000, inStock: true },
    ],
  },
  {
    id: "mmt-goa-package",
    name: "Goa Beach Holiday",
    brand: "MakeMyTrip",
    category: "Travel & Flights",
    rating: 4.5,
    badge: "New Launch",
    basePrice: 15999,
    description: "3N/4D Goa. Flights + hotel + breakfast. North Goa beaches, sightseeing, transfers.",
    images: ["https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=600&h=400&fit=crop"],
    specifications: { Duration: "3N / 4D", Destination: "North Goa", Inclusions: "Flights + Hotel + Breakfast", Transfers: "Included" },
    variants: [
      { id: "goa-3star", label: "3★ Hotel (Budget)", priceDelta: 0, inStock: true },
      { id: "goa-4star", label: "4★ Hotel (Deluxe)", priceDelta: 5000, inStock: true },
      { id: "goa-5star", label: "5★ Hotel (Luxury)", priceDelta: 15000, inStock: true },
    ],
  },
  {
    id: "mmt-kerala-package",
    name: "Kerala Backwaters Tour",
    brand: "MakeMyTrip",
    category: "Travel & Flights",
    rating: 4.7,
    badge: "Bestseller",
    basePrice: 24999,
    description: "5N/6D Kerala. Munnar hills, Alleppey houseboat, Kovalam beach. Flights + hotels + breakfast.",
    images: ["https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=600&h=400&fit=crop"],
    specifications: { Duration: "5N / 6D", Destinations: "Munnar + Alleppey + Kovalam", Inclusions: "Flight + Hotel + Breakfast + Transfers" },
    variants: [
      { id: "kerala-std", label: "Standard (3★ hotels)", priceDelta: 0, inStock: true },
      { id: "kerala-lux", label: "Luxury (5★ resorts)", priceDelta: 18000, inStock: true },
    ],
  },
  {
    id: "ease-blr-bkk",
    name: "Bangalore → Bangkok",
    brand: "EaseMyTrip",
    category: "Travel & Flights",
    rating: 4.2,
    basePrice: 12499,
    description: "Direct BLR→BKK. 3h 30m. Best price guaranteed on EaseMyTrip.",
    images: ["https://images.unsplash.com/photo-1508009603885-50cf7c579365?w=600&h=400&fit=crop"],
    specifications: { Route: "BLR → BKK", Duration: "3h 30m", Baggage: "20kg", Meals: "Included" },
    variants: [
      { id: "blr-bkk-eco", label: "Economy", priceDelta: 0, inStock: true },
      { id: "blr-bkk-flex", label: "Economy (Flexible)", priceDelta: 3000, inStock: true },
    ],
  },
  // ── HOTELS ───────────────────────────────────────────────────────
  {
    id: "cgh-coconut-lagoon",
    name: "Coconut Lagoon Resort",
    brand: "CGH Earth",
    category: "Hotels",
    rating: 4.9,
    badge: "Bestseller",
    basePrice: 18999,
    description: "Heritage kettuvallam houseboat resort on Lake Vembanad, Kerala. Per night, double occupancy, all meals.",
    images: ["https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=600&h=400&fit=crop", "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=600&h=400&fit=crop"],
    specifications: { Location: "Kumarakom, Kerala", "Check-in": "2:00 PM", Meals: "All-inclusive", Pool: "Infinity pool" },
    variants: [
      { id: "cgh-heritage-villa", label: "Heritage Villa (1 night)", priceDelta: 0, inStock: true },
      { id: "cgh-houseboat", label: "Private Houseboat (1 night)", priceDelta: 8000, inStock: true },
      { id: "cgh-premium", label: "Premium Suite (1 night)", priceDelta: 14000, inStock: true },
    ],
  },
  {
    id: "cgh-spice-village",
    name: "Spice Village Thekkady",
    brand: "CGH Earth",
    category: "Hotels",
    rating: 4.7,
    basePrice: 14500,
    description: "Eco-resort inside the Periyar Tiger Reserve. Tribal cottages, jungle safaris, spice trail walks.",
    images: ["https://images.unsplash.com/photo-1596178065887-1198b6148b2b?w=600&h=400&fit=crop"],
    specifications: { Location: "Thekkady, Kerala", Safaris: "Jungle + Boat", Cuisine: "Keralan + Multi", "Eco Cert": "Green Globe" },
    variants: [
      { id: "spice-std", label: "Standard Cottage (1 night)", priceDelta: 0, inStock: true },
      { id: "spice-prem", label: "Premium Cottage (1 night)", priceDelta: 5000, inStock: true },
    ],
  },
  {
    id: "goibibo-royal-orchid",
    name: "Royal Orchid Hotel Bengaluru",
    brand: "Goibibo",
    category: "Hotels",
    rating: 4.3,
    badge: "Hot Deal",
    basePrice: 4999,
    description: "4★ in Bengaluru CBD. King rooms, rooftop pool, complimentary breakfast. Book on 0% EMI.",
    images: ["https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=600&h=400&fit=crop"],
    specifications: { Location: "Bengaluru", Stars: "4★", Pool: "Rooftop", Breakfast: "Included", WiFi: "Free" },
    variants: [
      { id: "orchid-std", label: "Standard King Room", priceDelta: 0, inStock: true },
      { id: "orchid-del", label: "Deluxe Suite", priceDelta: 3000, inStock: true },
    ],
  },
  {
    id: "goibibo-taj-delhi",
    name: "Taj Hotel New Delhi",
    brand: "Goibibo",
    category: "Hotels",
    rating: 4.8,
    badge: "Top Pick",
    basePrice: 12999,
    description: "Iconic 5★ luxury. Trishna restaurant, spa, pool, and world-class service in the heart of Delhi.",
    images: ["https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=600&h=400&fit=crop"],
    specifications: { Location: "New Delhi", Stars: "5★", Pool: "Outdoor", Dining: "Multiple restaurants", Spa: "Full-service", WiFi: "Complimentary" },
    variants: [
      { id: "taj-del-sup", label: "Superior Room (1 night)", priceDelta: 0, inStock: true },
      { id: "taj-del-suite", label: "Junior Suite (1 night)", priceDelta: 8000, inStock: true },
    ],
  },
  // ── JEWELRY & BEAUTY ─────────────────────────────────────────────
  {
    id: "giva-lab-diamond",
    name: "Lab Diamond Solitaire Ring",
    brand: "Giva",
    category: "Jewelry & Beauty",
    rating: 4.7,
    badge: "New Launch",
    basePrice: 12999,
    description: "IGI-certified lab-grown diamond in 92.5 Sterling Silver. Ethically sourced, conflict-free.",
    images: ["https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=600&h=600&fit=crop", "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=600&h=600&fit=crop"],
    specifications: { Metal: "92.5 Sterling Silver", Stone: "Lab Grown Diamond (IGI)", Carat: "0.25ct", Finish: "Rhodium Plated", Warranty: "1 year" },
    variants: [
      { id: "giva-ring-s", label: "Size 6 (US)", priceDelta: 0, inStock: true },
      { id: "giva-ring-m", label: "Size 7 (US)", priceDelta: 0, inStock: true },
      { id: "giva-ring-l", label: "Size 8 (US)", priceDelta: 0, inStock: true },
    ],
  },
  {
    id: "giva-gold-chain",
    name: "18K Gold Chain Necklace",
    brand: "Giva",
    category: "Jewelry & Beauty",
    rating: 4.6,
    badge: "Bestseller",
    basePrice: 22999,
    description: "BIS Hallmarked 18K gold chain, 18 inches. Lobster clasp. Perfect for gifting and daily wear.",
    images: ["https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600&h=600&fit=crop"],
    specifications: { Metal: "18K Gold", Purity: "BIS Hallmarked", Length: "18 inches", Weight: "3.2g", Warranty: "1 year" },
    variants: [
      { id: "gold-chain-16", label: "16 inch", priceDelta: -2000, inStock: true },
      { id: "gold-chain-18", label: "18 inch", priceDelta: 0, inStock: true },
      { id: "gold-chain-20", label: "20 inch", priceDelta: 2500, inStock: true },
    ],
  },
  {
    id: "giva-silver-set",
    name: "Silver Earring & Pendant Set",
    brand: "Giva",
    category: "Jewelry & Beauty",
    rating: 4.5,
    basePrice: 2499,
    description: "925 Sterling Silver matching earring + pendant with cubic zirconia. Hypoallergenic.",
    images: ["https://images.unsplash.com/photo-1535632787350-4e68ef0ac584?w=600&h=600&fit=crop"],
    specifications: { Metal: "925 Sterling Silver", Stone: "Cubic Zirconia", Hypoallergenic: "Yes", Packaging: "Gift pouch" },
    variants: [
      { id: "silver-set-rose", label: "Rose Gold plated", priceDelta: 300, inStock: true },
      { id: "silver-set-plain", label: "Rhodium plated", priceDelta: 0, inStock: true },
    ],
  },
  {
    id: "giva-bridal-set",
    name: "Bridal Kundan Jewellery Set",
    brand: "Giva",
    category: "Jewelry & Beauty",
    rating: 4.8,
    badge: "Bestseller",
    basePrice: 8999,
    description: "Complete bridal set: necklace, earrings, maang tikka & nose ring. Kundan work with meenakari enamel.",
    images: ["https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?w=600&h=600&fit=crop"],
    specifications: { Set: "Necklace + Earrings + Maang Tikka + Nose Ring", Style: "Kundan + Meenakari", Plating: "Gold plated", Occasion: "Bridal / Festive" },
    variants: [
      { id: "bridal-red", label: "Red Meenakari", priceDelta: 0, inStock: true },
      { id: "bridal-green", label: "Green Meenakari", priceDelta: 0, inStock: true },
      { id: "bridal-blue", label: "Royal Blue", priceDelta: 500, inStock: true },
    ],
  },
  // ── FURNITURE & HOME ─────────────────────────────────────────────
  {
    id: "wakefit-ortho-mattress",
    name: "Orthopaedic Memory Foam Mattress",
    brand: "Wakefit",
    category: "Furniture & Home",
    rating: 4.6,
    badge: "Bestseller",
    basePrice: 14999,
    description: "7-zone orthopaedic memory foam with cooling gel. 100-night free trial. 10-year warranty. Free delivery + setup.",
    images: ["https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=600&h=400&fit=crop"],
    specifications: { Foam: "Memory Foam + HR Base", "Trial Period": "100 nights", Warranty: "10 years", Delivery: "Free + Setup" },
    variants: [
      { id: "wakefit-single", label: "Single (78×36 in)", priceDelta: 0, inStock: true },
      { id: "wakefit-double", label: "Double (78×48 in)", priceDelta: 3000, inStock: true },
      { id: "wakefit-queen", label: "Queen (78×60 in)", priceDelta: 6000, inStock: true },
      { id: "wakefit-king", label: "King (78×72 in)", priceDelta: 9000, inStock: true },
    ],
  },
  {
    id: "wakefit-sofa",
    name: "L-Shape Fabric Sofa",
    brand: "Wakefit",
    category: "Furniture & Home",
    rating: 4.4,
    basePrice: 28999,
    description: "Premium L-shape sofa. High-density foam, stain-resistant fabric, solid wood legs. Free assembly.",
    images: ["https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?w=600&h=400&fit=crop"],
    specifications: { Material: "Fabric + Wood Frame", Dimensions: "280×160 cm", Assembly: "Free", Warranty: "1 year" },
    variants: [
      { id: "sofa-grey", label: "Slate Grey", priceDelta: 0, inStock: true },
      { id: "sofa-blue", label: "Ocean Blue", priceDelta: 1000, inStock: true },
      { id: "sofa-beige", label: "Warm Beige", priceDelta: 0, inStock: true },
    ],
  },
  {
    id: "ikea-billy-shelf",
    name: "BILLY Bookcase",
    brand: "IKEA",
    category: "Furniture & Home",
    rating: 4.5,
    basePrice: 4999,
    description: "Iconic BILLY bookcase with adjustable shelves. Easy assembly. Fits any room.",
    images: ["https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=600&h=400&fit=crop"],
    specifications: { Material: "Particleboard", Dimensions: "80×28×202 cm", Shelves: "5 adjustable", Warranty: "10 years" },
    variants: [
      { id: "billy-white", label: "White", priceDelta: 0, inStock: true },
      { id: "billy-oak", label: "Oak Effect", priceDelta: 1000, inStock: true },
      { id: "billy-black", label: "Black-Brown", priceDelta: 500, inStock: true },
    ],
  },
  // ── APPLIANCES ───────────────────────────────────────────────────
  {
    id: "lg-oled-tv",
    name: "LG OLED C4 65\"",
    brand: "LG",
    category: "Appliances",
    rating: 4.8,
    badge: "Top Pick",
    basePrice: 189999,
    description: "65-inch OLED evo panel. α9 AI Processor Gen7. Dolby Vision IQ + Atmos. The TV critics choose.",
    images: ["https://images.unsplash.com/photo-1593359677879-a4bb92f4348a?w=600&h=400&fit=crop"],
    specifications: { Panel: "65\" OLED evo", Processor: "α9 Gen7 AI", HDR: "Dolby Vision IQ", Audio: "Dolby Atmos", "Smart OS": "webOS 24", Refresh: "120Hz" },
    variants: [
      { id: "lg-oled-55", label: "55 inch", priceDelta: -40000, inStock: true },
      { id: "lg-oled-65", label: "65 inch", priceDelta: 0, inStock: true },
      { id: "lg-oled-77", label: "77 inch", priceDelta: 60000, inStock: true },
    ],
  },
  {
    id: "whirlpool-washing",
    name: "Whirlpool 7kg Front Load",
    brand: "Whirlpool",
    category: "Appliances",
    rating: 4.4,
    basePrice: 34999,
    description: "7kg front-load washing machine. 6th Sense technology. 1400 RPM. 12 wash programs. 5-star energy rating.",
    images: ["https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&h=400&fit=crop"],
    specifications: { Capacity: "7 kg", Type: "Front Load", RPM: "1400", Programs: "12", Energy: "5 Star", Warranty: "3 years" },
    variants: [
      { id: "wp-7-white", label: "White", priceDelta: 0, inStock: true },
      { id: "wp-8-silver", label: "8kg / Silver", priceDelta: 5000, inStock: true },
    ],
  },
  {
    id: "lg-fridge",
    name: "LG 655L French Door Refrigerator",
    brand: "LG",
    category: "Appliances",
    rating: 4.6,
    badge: "New Launch",
    basePrice: 119999,
    description: "655L InstaView French door refrigerator. Knock to see inside. Hygiene Fresh+. Linear Compressor. 5-star.",
    images: ["https://images.unsplash.com/photo-1584568694244-14fbdf83bd30?w=600&h=400&fit=crop"],
    specifications: { Capacity: "655L", Type: "French Door", "InstaView": "Yes", Compressor: "Linear Inverter", Energy: "5 Star", Warranty: "10 years compressor" },
    variants: [
      { id: "lg-fridge-silver", label: "Shiny Steel", priceDelta: 0, inStock: true },
      { id: "lg-fridge-black", label: "Matte Black", priceDelta: 5000, inStock: true },
    ],
  },
  // ── WEARABLES ────────────────────────────────────────────────────
  {
    id: "apple-watch-s10",
    name: "Apple Watch Series 10",
    brand: "Apple",
    category: "Wearables",
    rating: 4.8,
    badge: "New Launch",
    basePrice: 46900,
    description: "Thinnest Apple Watch. Always-on Retina display, advanced health sensors, 18-hour battery.",
    images: ["https://images.unsplash.com/photo-1551816230-ef5deaed4a26?w=600&h=600&fit=crop"],
    specifications: { Display: "1.9″ Always-On", Sensors: "Heart, ECG, SpO2, Temp", Battery: "18 hours", Water: "50m waterproof", GPS: "Dual-frequency" },
    variants: [
      { id: "aws10-41-midnight", label: "41mm / Midnight", priceDelta: 0, inStock: true },
      { id: "aws10-45-starlight", label: "45mm / Starlight", priceDelta: 3000, inStock: true },
      { id: "aws10-45-steel", label: "45mm / Stainless Steel", priceDelta: 16000, inStock: true },
    ],
  },
  {
    id: "samsung-galaxy-watch7",
    name: "Galaxy Watch 7",
    brand: "Samsung",
    category: "Wearables",
    rating: 4.4,
    basePrice: 29999,
    description: "BioActive sensor with body composition analysis. Sleep coaching, 3-day battery, Galaxy AI.",
    images: ["https://images.unsplash.com/photo-1434494878577-86c23bcb06b9?w=600&h=600&fit=crop"],
    specifications: { Display: "1.5″ Super AMOLED", Battery: "3 days", Water: "5ATM", OS: "Wear OS 5", GPS: "L1 + L5" },
    variants: [
      { id: "gw7-40-green", label: "40mm / Forest Green", priceDelta: 0, inStock: true },
      { id: "gw7-44-silver", label: "44mm / Silver", priceDelta: 3000, inStock: true },
    ],
  },
  {
    id: "garmin-forerunner",
    name: "Forerunner 965",
    brand: "Garmin",
    category: "Wearables",
    rating: 4.7,
    badge: "Bestseller",
    basePrice: 59999,
    description: "Premium running GPS smartwatch. AMOLED display, 31-day battery, advanced training metrics and recovery tools.",
    images: ["https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&h=600&fit=crop"],
    specifications: { Display: "1.4\" AMOLED", Battery: "31 days (GPS: 31h)", Sports: "Running, Cycling, Swimming +", Training: "VO2 Max, HRV, Race Predictor", Water: "5ATM" },
    variants: [
      { id: "fr965-black", label: "Black / Black band", priceDelta: 0, inStock: true },
      { id: "fr965-white", label: "White / Whitestone band", priceDelta: 0, inStock: true },
    ],
  },
  // ── GAMING ───────────────────────────────────────────────────────
  {
    id: "ps5-slim",
    name: "PlayStation 5 Slim",
    brand: "PlayStation",
    category: "Gaming",
    rating: 4.8,
    badge: "Bestseller",
    basePrice: 54990,
    description: "Slimmer design, same PS5 power. 1TB SSD, 4K gaming at 120fps, DualSense haptic feedback.",
    images: ["https://images.unsplash.com/photo-1607853202273-232359894ca9?w=600&h=600&fit=crop"],
    specifications: { CPU: "AMD Zen 2 8-core", GPU: "AMD RDNA 2 10.28 TFLOPS", Storage: "1TB SSD", Resolution: "Up to 4K", "Frame Rate": "Up to 120fps", "Ray Tracing": "Yes" },
    variants: [
      { id: "ps5-disc", label: "Disc Edition", priceDelta: 0, inStock: true },
      { id: "ps5-digital", label: "Digital Edition", priceDelta: -5000, inStock: true },
    ],
  },
  // ── CAMERAS ──────────────────────────────────────────────────────
  {
    id: "canon-eos-r8",
    name: "Canon EOS R8",
    brand: "Canon",
    category: "Cameras",
    rating: 4.6,
    basePrice: 139999,
    description: "Full-frame mirrorless at an accessible price. 24.2MP, 40fps burst, Dual Pixel CMOS AF, 4K video.",
    images: ["https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=600&h=600&fit=crop"],
    specifications: { Sensor: "24.2MP Full-Frame CMOS", AF: "Dual Pixel CMOS AF II", Burst: "40fps electronic", Video: "4K 60fps", Stabilization: "In-lens (IS)", Weight: "461g" },
    variants: [
      { id: "eosr8-body", label: "Body Only", priceDelta: 0, inStock: true },
      { id: "eosr8-kit", label: "Body + RF 24-50mm Kit Lens", priceDelta: 20000, inStock: true },
    ],
  },
  // ── FITNESS ──────────────────────────────────────────────────────
  {
    id: "garmin-fenix7",
    name: "Fenix 7X Pro Solar",
    brand: "Garmin",
    category: "Fitness",
    rating: 4.8,
    badge: "Top Pick",
    basePrice: 79999,
    description: "Multi-sport GPS with solar charging. 37-day battery. Sapphire glass lens. Topographic maps. Military-grade durability.",
    images: ["https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=600&h=600&fit=crop"],
    specifications: { Battery: "37 days (solar)", Display: "1.4\" MIP + Solar", Durability: "MIL-STD-810", Maps: "Worldwide topo", Sports: "100+ activities", Water: "10ATM" },
    variants: [
      { id: "fenix7x-black", label: "Black / Black band", priceDelta: 0, inStock: true },
      { id: "fenix7x-silver", label: "Silver / Grey band", priceDelta: 3000, inStock: true },
    ],
  },
];

export const EMI_TENURES = [3, 6, 9, 12, 18, 24];

export const NEARBY_STORES_BY_CITY: Record<string, { name: string; address: string; dist: string; brand: string; category: string }[]> = {
  Gurugram: [
    { name: "Croma Sector 14", address: "Plot No. 12, Sector 14, DLF Phase 1, Gurugram 122001", dist: "0.8 KM", brand: "Croma", category: "Electronics" },
    { name: "Vijay Sales MG Road", address: "MG Road, DLF Phase 2, Gurugram 122002", dist: "1.4 KM", brand: "Vijay Sales", category: "Electronics" },
    { name: "Wakefit Experience Center", address: "Global Foyer Mall, Golf Course Road, Gurugram 122002", dist: "2.1 KM", brand: "Wakefit", category: "Furniture" },
    { name: "Apple Premium Reseller Ambience", address: "Ambience Mall, NH-48, Gurugram 122001", dist: "3.0 KM", brand: "Apple", category: "Electronics" },
    { name: "Samsung Smart Plaza Galleria", address: "Galleria Market, DLF Phase 4, Gurugram 122009", dist: "3.5 KM", brand: "Samsung", category: "Electronics" },
    { name: "Giva Cyberhub", address: "DLF Cyber City, Cyberhub, Gurugram 122002", dist: "4.2 KM", brand: "Giva", category: "Jewelry" },
    { name: "LG Exclusive Brand Shop", address: "Sector 56, Gurugram, Haryana 122011", dist: "5.1 KM", brand: "LG", category: "Appliances" },
  ],
  Mumbai: [
    { name: "Croma Powai", address: "Galleria Mall, Hiranandani, Powai, Mumbai 400076", dist: "1.2 KM", brand: "Croma", category: "Electronics" },
    { name: "Apple iStore Bandra", address: "Linking Road, Bandra West, Mumbai 400050", dist: "2.3 KM", brand: "Apple", category: "Electronics" },
    { name: "IKEA Navi Mumbai", address: "Turbhe, Navi Mumbai 400705", dist: "5.1 KM", brand: "IKEA", category: "Furniture" },
    { name: "Giva Juhu", address: "Juhu Tara Road, Juhu, Mumbai 400049", dist: "3.8 KM", brand: "Giva", category: "Jewelry" },
    { name: "Samsung Experience Andheri", address: "Infiniti Mall, Andheri West, Mumbai 400053", dist: "4.5 KM", brand: "Samsung", category: "Electronics" },
    { name: "Wakefit Lower Parel", address: "Phoenix Palladium, Lower Parel, Mumbai 400013", dist: "6.0 KM", brand: "Wakefit", category: "Furniture" },
  ],
  Bengaluru: [
    { name: "Croma Koramangala", address: "1st Block, Koramangala, Bengaluru 560034", dist: "0.9 KM", brand: "Croma", category: "Electronics" },
    { name: "Apple Authorised UB City", address: "UB City Mall, Vittal Mallya Road, Bengaluru 560001", dist: "2.0 KM", brand: "Apple", category: "Electronics" },
    { name: "Wakefit Indiranagar", address: "100 Feet Road, Indiranagar, Bengaluru 560038", dist: "2.7 KM", brand: "Wakefit", category: "Furniture" },
    { name: "IKEA Electronics City", address: "Neeladri Road, Electronics City, Bengaluru 560100", dist: "7.5 KM", brand: "IKEA", category: "Furniture" },
    { name: "Samsung Smart Plaza MG Road", address: "Brigade Road, Bengaluru 560025", dist: "3.1 KM", brand: "Samsung", category: "Electronics" },
    { name: "Giva Koramangala", address: "5th Block, Koramangala, Bengaluru 560095", dist: "1.5 KM", brand: "Giva", category: "Jewelry" },
  ],
  Delhi: [
    { name: "Croma Select Citywalk", address: "A-3, District Centre, Saket, New Delhi 110017", dist: "1.5 KM", brand: "Croma", category: "Electronics" },
    { name: "Apple CP Premium Reseller", address: "Connaught Place, New Delhi 110001", dist: "3.2 KM", brand: "Apple", category: "Electronics" },
    { name: "Giva Lajpat Nagar", address: "Central Market, Lajpat Nagar, New Delhi 110024", dist: "2.8 KM", brand: "Giva", category: "Jewelry" },
    { name: "IKEA Dwarka", address: "Sector 21 Metro, Dwarka, New Delhi 110075", dist: "8.5 KM", brand: "IKEA", category: "Furniture" },
    { name: "Samsung Flagship Vasant Kunj", address: "DLF Promenade, Vasant Kunj, New Delhi 110070", dist: "4.1 KM", brand: "Samsung", category: "Electronics" },
    { name: "LG Brand Shop Karol Bagh", address: "Ajmal Khan Road, Karol Bagh, New Delhi 110005", dist: "5.5 KM", brand: "LG", category: "Appliances" },
  ],
  Hyderabad: [
    { name: "Croma Banjara Hills", address: "Road No. 2, Banjara Hills, Hyderabad 500034", dist: "1.1 KM", brand: "Croma", category: "Electronics" },
    { name: "Apple iStore Inorbit", address: "Inorbit Mall, Madhapur, Hyderabad 500081", dist: "2.4 KM", brand: "Apple", category: "Electronics" },
    { name: "Wakefit Jubilee Hills", address: "Road No. 36, Jubilee Hills, Hyderabad 500033", dist: "3.0 KM", brand: "Wakefit", category: "Furniture" },
    { name: "Samsung Experience Gachibowli", address: "DLF Cyber City, Gachibowli, Hyderabad 500032", dist: "3.8 KM", brand: "Samsung", category: "Electronics" },
    { name: "Giva Banjara Hills", address: "Road No. 10, Banjara Hills, Hyderabad 500034", dist: "1.9 KM", brand: "Giva", category: "Jewelry" },
  ],
};

export const CITIES = Object.keys(NEARBY_STORES_BY_CITY);
